apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  minecraft
  name:  minecraft-deployment
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  minecraft
  template:
    metadata:
      labels:
        app:  minecraft
    spec:
      containers:
      - name:  minecraft
        image:  meat/minecraft
        ports:
        - containerPort: 25565
        env:
        - name: WORLD_ZIP
          valueFrom:
            secretKeyRef:
              key: world-zip
              name: minecraft-world-zip
        - name: NETHER_ZIP
          valueFrom:
            secretKeyRef:
              key: nether-zip
              name: minecraft-nether-zip
        - name: PLUGINS_ZIP
          valueFrom:
            secretKeyRef:
              key: plugins-zip
              name: minecraft-plugins-zip
        - name: BUCKET_PATH
          valueFrom:
            secretKeyRef:
              key: bucket-path
              name: minecraft-bucket-path
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
        - mountPath: /minecraft/whitelist.json
          subPath: whitelist.json
          name: minecraft-server-whitelist
        - mountPath: /minecraft/ops.json
          subPath: ops.json
          name: minecraft-server-ops
        - mountPath: /minecraft/server.properties
          subPath: server.properties
          name: minecraft-server-properties
        - mountPath: /minecraft/world
          name: minecraft-world
        - mountPath: /minecraft/world_nether
          name: minecraft-nether
        - mountPath: /minecraft/plugins
          name: minecraft-plugins
      volumes:
      - name: google-cloud-key
        secret:
          secretName: google-cloud-key
      - name: minecraft-server-whitelist
        configMap:
          name: minecraft-server-whitelist
      - name: minecraft-server-ops
        configMap:
          name: minecraft-server-ops
      - name: minecraft-server-properties
        configMap:
          name: minecraft-server-properties
      - name: minecraft-world
        persistentVolumeClaim:
          claimName: minecraft-world-pv-claim
      - name: minecraft-nether
        persistentVolumeClaim:
          claimName: minecraft-nether-pv-claim
      - name: minecraft-plugins
        persistentVolumeClaim:
          claimName: minecraft-plugins-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  minecraft
  name:  minecraft-service
  namespace: minecraft
spec:
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
  selector:
    app:  minecraft
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-world-pv-claim
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-nether-pv-claim
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-plugins-pv-claim
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
